[package]
name = "ltc-sys"
version = "0.1.0"
authors = ["Johannes Maibaum <jmaibaum@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
