[package]
name = "libltc"
version = "0.1.0"
authors = ["Johannes Maibaum <jmaibaum@gmail.com>"]
edition = "2018"
license = "LGPL-3.0-or-later"

[dependencies]
ltc-sys = {git = "https://github.com/jmaibaum/ltc-sys.git"}
